### ISSUE TITLE
Where is OIH Plus at home?

### ISSUE THREAD

**Issue by blaggacao** [openintegrationhub/openintegrationhub#1004]
We just decided to bet on OIH over syndesis for it's several significant design improvements such as Data Hub, ILS and Dispatcher Service. And then I read that development of [1.x - Legacy](https://github.com/openintegrationhub/openintegrationhub/releases/tag/v1.x) stops.

The OIH Plus project goals are quite vague https://www.h-brs.de/de/open-integration-hub-plus (at the technical level).

And I've no idea where / how transition to OIH Plus is going to happen.

Clarification would be much appreciated to vet our upcoming investment in person-hours.

**Comment by RobinBrinkmann** [comment]
Hi, thanks for your feedback and opening up issues. Sorry for the uncertainty this caused. The good news: Central data storage (via Data Hub) and the Hub & Spoke model are a big part of the upcoming development. We did want to get the new connector architecture set up first, but the other services will follow soon. We will improve our release process and roadmap communication as well.

In order to better understand your requirements and share more details on our roadmap, I will also reach out directly via mail so we can arrange a call.
