### ISSUE TITLE
Authorization Error

### ISSUE THREAD

**Issue by pdsxin** [openintegrationhub/openintegrationhub#1052]
After going through the "Getting Started/ Local Installation" I installed the OIH on my windows system. However, when i try to login in the web-ui with the admin (admin@openintegrationhub.com/somestring) i get the error:

     Failed to load resource: http://flow-repository.localoih.com/flows 
     the server responded with a status of 401 (Unauthorized)

When i try go to  http://flow-repository.localoih.com/flows  directly i receive the message  {"errors":[{"message":"Missing authorization header.","code":401}]}. 

![2020-09-17 17_45_45-Window](https://user-images.githubusercontent.com/71007395/93494838-c4363780-f90d-11ea-824f-f650c4b65aca.png)

**Comment by RobinBrinkmann** [comment]
Hi @pdsxin 
did you try logging in with the user created in this step: https://openintegrationhub.github.io//docs/Getting%20Started/LocalInstallationGuide.html#create-a-service-account?

**Comment by pdsxin** [comment]
Hello,
thanks for the answer. yes i also tried to login with the user/pw (test@test.de/asd) and created even moren users, but i always get the same error.

**Comment by SvenHoeffler** [comment]
@pdsxin Did you happen to adjust any of the configuration during the local installation at all?

Anyway, directly going to `http://flow-repository.localoih.com/flows` resulting in a 401 is expected behaviour, as it's a privileged endpoint and your browser doesn't send an authentication header by default. As are all the other 401s there, as the UI apparently attempts to ping them with an invalid auth header.

Could you open up the network tab of your browser's dev tools, attempt to login again, and then show us screenshots of the login request and its response? That should help clear up why exactly the login fails.

**Comment by pdsxin** [comment]
@SvenHoeffler no i tried to do it just like in the instruction.

I deleted the minikube and went through all the steps from the start again and now i can login. maybe i had typed in a wrong token. Thank you for your quick responses

**Comment by RobinBrinkmann** [comment]
Strange, but glad it works now! Let us know if you need further support.

---- close issue ----
