### ISSUE TITLE
Validate and formalize connector message format.

### ISSUE THREAD

**Issue by SvenHoeffler** [openintegrationhub/openintegrationhub#1078]
Currently, the format of messages expected and put out by connectors is this:

```
{
    id: string,
    attachments: {},
    body: {
        data: {},
        meta: {
            recordUid: string,
            oihUid: string,
        }
    },
    headers: {},
    metadata: {},
  }
```

This is something a legacy format, as this was the one used by the elasticio platform at the time. Some connectors still use the function `newMessageWithBody()` supplied by an elasticio dependency to create this function. Others use a more lightweight inbuilt helper function to achieve the same (e.g. https://github.com/openintegrationhub/placetel-connector/blob/578311b1049430ce1f32037d2c74582440cf472c/lib/utils/helpers.js#L88)

However, in practice, only the `body` field is ever really used. There may be a future use-case for the `attachments` field, but so far it is not used by any connector. As such, we should re-evaluate which fields are actually relevant and, if necessary, adjust the format to a simpler version. The finalized format, whether any changes are made or not, should then be explicitly detailed in documentation.

---

**Acceptance Criteria:**
- [x] Discuss current message format
- [x] If format is changed: Adjust current connectors to use new format
- [x] Update documentation

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by weberjm** [comment]
As you mentioned, this format is derived from the legacy implementation of elastic.io messaging. I have had trouble finding specific descriptions in either OIH or Elastic documentation to clarify the full usage of each field. The closest I came was [this page](https://docs.elastic.io/guides/using-attachments.html), regarding the ability to use the attachment field in an elastic message.

The first item that pops out at me from the above comment, is that we have both message metadata (`metadata`) and body metadata (`meta`) parameters. While it is true that we could have metadata at both levels, would it not be more concise to say that any field at the top level is a metadata field, used for messaging implementation, except for the attachment and body parameters?

There are two questions we need to answer to come up with a solid solution here:
1) Which fields are needed to fully pass data through a flow, including flexibility for currently unrealized use cases?
2) Where is the separation of responsibility for providing each element? For instance, the trigger or action function should not be responsible for properly assembling a message structure. At most, it should know about data/body fields and about attachments. The message packaging should be handled by the ferryman.

**Comment by SvenHoeffler** [comment]
As it stands, these are the fields currently used:

- `body.data`: Is used 100% of the time by the connector itself, as it contains the actual payload. It is filled by Triggers, and read/modified by Actions.
- `body.meta`: Is used whenever ID linking or Hub&Spoke are in use. Contains one key `recordUid` that must be accessible to the connector. Can currently also optionally contain `oihUid` or `applicationUid`, though those are not relevant for the connector itself and could be filled automatically based on flow configuration.

All the others are not currently in use, and to my knowledge never have been. However, `attachments` may well become relevant in the future, and may need to be accessible to connectors.

**Comment by weberjm** [comment]
Looking a little deeper into the elastic components, it looks like their message format expanded somewhat due to specific components. 
- `headers`: this root-level field appears to be set in the REST component, and is used to pass on the HTTP response headers when returned. Left out of the "standard message format," this component also adds a `statusCode` and `statusMessage` root-level field.

In most cases, I believe the component itself should be handling specific HTTP response items, not passing them further into the flow. However, in case that use case is desired, we could consider those items as part of the `body`/`data` block (or potentially `metadata`, but I think that should remain for OIH metadata.

My proposal would then be to have the following root objects:
- `id`: (UUID) If necessary for any use case? We could also consider dropping the message ID, as message queue providers would likely also wrap any of our messages in their own ID/Payload wrapper.
- `data`: (Object) The primary payload for the message, which could include various fields (see below)
- `attachments`: (Array) [optional] Any file objects, which should be handled with an attachment storage service or other external mechanism
- `metadata`: (Object) Any OIH metadata to be added, such as the examples above with linking / hub-and-spoke data

### Example from a REST Component
```
{
  id: string,
  data: {
    body: { ... },
    status: 200,
    headers: {...},
    ...
  },
  attachments: [....],
  metadata: {
    recordUid: string,
    oihUid: string,
  }
}
```

### Example from a CRM Component
```
{
  id: string,
  data: {
    person: {
      firstName: string,
      ...
    }
  },
  attachments: [....],
  metadata: {
    recordUid: string,
    oihUid: string,
  }
}
```

**Comment by SvenHoeffler** [comment]
I've just double-checked, the `id` field does not seem to be necessary on the connector-level at all. If it is omitted, the Component Orchestrator will simply insert it and then continue as normal. 

I agree that it's probably best to put the `data` field directly on the top level, and use the existing `metadata` for, well, metadata, maintaining a clear separation of concerns.

**Comment by SvenHoeffler** [comment]
As per the most recent discussion, we will be going forward with the proposal of @weberjm above. The next steps are updating existing connectors and documentation.

**Comment by SvenHoeffler** [comment]
Most existing connectors have been migrated to the new format. Moving this to review pending further testing and potential bugfixes.
