### ISSUE TITLE
Improve Component Orchestrator Scalability

### ISSUE THREAD

**Issue by RobinBrinkmann** [openintegrationhub/openintegrationhub#1079]
Current load testing showed that the Component Orchestrator can be a bottleneck for the overall scalability of the framework as it is not horizontally scalable. Currently all active replicas would receive and respond to all events which will result in duplicate flows. 

We need to investigate whether event subscribers can provide a subscriber key as is done i.e. in google pub/sub.

**Comment by weberjm** [comment]
When we move forward on this issue, we should look at clearly defining the use cases for our Event Bus and for our different utilisation of messaging and eventing systems. As discussed in #324, we currently have a situation where our use of events and messages are bleeding into each other's definitions. 

In this case, I think there are two primary options for enabling horizontal scalability in the Orchestrator:

1. Putting a load balancer in front of the Orchestrator, and passing events along round-robin. Should we need to remain stateful between calls from a single flow, we can use Affinity or a similar feature of the messaging queue to make sure a single node handles each session.
2. Instead of using events in this case, ensuring we use messaging, with a two-step queue that requires confirmation that a message has been received and successfully processed.

More generally, we should make sure that we utilize events and messages for their standard use cases: Events are used when an action occurs and the Emitter does not care what other services do with that. Messages should be used when (as in this case) two services must work in coordination to implement the functionality.
