### ISSUE TITLE
Test Hub & Spoke functionality under 20.2.0

### ISSUE THREAD

**Issue by RobinBrinkmann** [openintegrationhub/openintegrationhub#1082]
Hub & Spoke style integration is one key scenario for Open Integration Hub. The focus of the latest rework was on adding global connectors and integrate applications in a 1:1 fashion. In theory the H&S setup should not be affected much, but we need to do extensive testing and possibly some adjustments.

**Comment by SvenHoeffler** [comment]
As expected, Hub & Spoke is not currently entirely functional. However, the fixes necessary do not seem too daunting.

The main issue is that the system still assumes separate adapters and transformers, and only builds flows containing both adapters and transformers. Naturally, this will cause a failure if using newer connectors that combine adapter and transformer functions.

As such, the only change that seems necessary would be adjusting the automatic flow creation in the Dispatcher Service to no longer use separate transformer steps. Additionally, the App Directory should be adjusted to no longer save Transformer-specific data per app.

Also, the SDF-Adapter needed to be switched to Ferryman, but that has already been done.

The automatic flow creation still works in principle (albeit creating old-style flows as discussed above), and the routing logic should also still function as before.

**Comment by SvenHoeffler** [comment]
With the latest updates to dispatcher service and SDF-Adapter, the Hub&Spoke functionality is now restored.

However, there is one limitation: The automatic starting of inbound flows upon receiving data from a related outbound flow will produce an error if a secret is used in the same flow. This is due to changes in how the secrets are fetched, which now happens inside the Ferryman rather than the Orchestrator. 

If the flows are instead simply started manually, everything ought to work as before.

**Comment by SvenHoeffler** [comment]
Since the basic functionality is restored, this issue can be considered resolved. The issue with the automatic starting is logged in #1109, and can be worked on if and when it becomes necessary.
