### ISSUE TITLE
Local installation: access with proxy verbs/urls not working due to CORS

### ISSUE THREAD

**Issue by huberv** [openintegrationhub/openintegrationhub#1128]
As a developer, I want to set up OIH locally, using Minikube on Docker for Desktop (under Windows), to get started swiftly.

When working through the instructions for setting up the OIH in the getting started guide at

https://openintegrationhub.github.io/docs/Getting%20Started/LocalInstallationGuide.html

I get stuck at the step "Host Rules Setup": Should all hostnames really point to one and the same IP address? That seems unlikely, although I'm by no means a K8s expert.

I tried to get the admin token by
1. Running `kubectl proxy` in a terminal and
2. Using the URL http://localhost:8001/api/v1/namespaces/oih-dev-ns/services/iam/proxy/login in Postman

However, I get a 500 with response 
```json
{
    "message": "Not allowed by CORS"
}
```

Refer to the attached screenshot.

It's quite likely I just got something wrong... could you please advise on how exactly to invoke the OIH apis in the local minikube setup w/o tinkering around with the HOSTS file?

Any help is highly appreciated!

Thanks and kind regards,
Valentin

![27-11-_2020_09-20-33](https://user-images.githubusercontent.com/16324140/100427636-0957b200-3093-11eb-8307-0d57360a8a48.png)

**Comment by heggert** [comment]
Hi @huberv 

you need to provide a specific environment variable called "IAM_ORIGINWHITELIST" to IAM service. 
Every host, from which requests to IAM should be permitted, must be listed here (comma separated).

For instance

`IAM_ORIGINWHITELIST=openintegrationhub.com,iam.oih-dev-ns.svc.cluster.local:3099,localhost,127.0.0.1`

**Comment by huberv** [comment]
Hi @heggert, 
thanks for the swift reply! I noticed that "127.0.0.1" is already contained in the default value for this env variable, and using the URL 127.0.0.1:8001/api/v1/namespaces/oih-dev-ns/services/iam/proxy/login works - thanks a lot!

**Comment by weberjm** [comment]
Hi Valentin,

Regarding your first question, the Host Rules Setup: Yes, all used subdomains point to the same IP address. This is the minikube cluster IP address, and is the only externally accessible IP for the system (without additional configuration). The Ingress object is responsible then for routing the request to the correct service internally.

After this is setup, if following the Local Installation Guide, you should be able to login via the URL: http://iam.localoih.com/login. 

As @heggert mentioned above, the CORS issue comes from the whitelist provided to the service. As a quick workaround to obtain access via Postman, you can simply declare an "origin" header which matches one of the URLs in the current whitelist.

We have not tested the system to see how it behaves using the `kubectl proxy` call. You could use the `kubectl cluster-info` command to see if the services are declaring a proxy URL. https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-services-running-on-the-cluster. It looks like you are reaching an OIH endpoint, but it does say in the listed documentation that
> Proxies may cause problems for some web applications.

It could be that our application does not work well with the kubectl proxy, considering it is also using the Ingress for similar functions.

Another option if you don't want to update your HOSTS file, you could also consider using [port forwarding](https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/) to access the specific cluster services. Again, I have not tested this setup extensively to verify if it works with our minikube setup, but have been able to at least successfully login (again, by setting an "origin" header as mentioned above).

Let us know if you continue to experience problems!

**Comment by huberv** [comment]
Summary: Using `kubectl proxy` works (on my machine :-)) if you use 127.0.0.1 as hostname, since this is contained in the whitelist out of the box

**Comment by huberv** [comment]
@weberjm So, I came across a follow-up issue: after deploying all the service seems to work and the pods are up and running happily. However, when I try to open the web ui via the URL 

http://127.0.0.1:8001/api/v1/namespaces/oih-dev-ns/services/web-ui/proxy/

I do get an 404 when the react app tries to load 

GET http://127.0.0.1:8001/config

I think this is due to the line 

```js
updateConfig((await axios.get('/config')).data);
```

in `services\web-ui\src\index.js`, where the `/config` could/should be replaced with the relative path `config`, I guess.
Is there any specific reason why the path is currently an absolute one?

Anyhow, is there a way for my to test this? Is seems like the k8s files under the minikube folder pull their images from the docker registry. Could I somehow manage to build the containers on my own and make the minikube files use these containers instead?

**Comment by weberjm** [comment]
@huberv The problem with the config endpoint comes from the web-ui service operating on the assumption that it runs at the base (sub-)domain level, not as a subdirectory:
https://github.com/openintegrationhub/openintegrationhub/blob/89eb9bb99834188edf459d8ee912f2f6341c4440/services/web-ui/src/setupProxy.js#L94-L96
Here you see that it handles a call to the `/config`endpoint, which would be handled correctly from your referenced line: https://github.com/openintegrationhub/openintegrationhub/blob/89eb9bb99834188edf459d8ee912f2f6341c4440/services/web-ui/src/index.js#L40 if the service is running as http://web-ui.localoih.com, for example.

Because this is an axios call, it is using relative URLs. I am not sure at the time this line is called, what exactly the URL context will be. It is possible that using a URL relative to the current path would work, rather than calling relative to the webroot.

**Testing:** Yes, it is possible to do local testing! There are a couple example implementations under the `dev-tools/` folder. It basically comes down to two options:
1. Ensure that your Deployment ImagePullPolicy is not set to "Always." Do whatever updates you want and then build your image using the same tag (or, if you want to change the image tag value in the Deployment script, you can also pick a new tag) into the minikube environment (Use `eval $(minikube docker-env)` so that your builds will go into minkube's image repo). Then, when you delete the current pod, minikube should rebuild the pod using your new image.
2. There is a way to use your local dev environment to load your files into a base node image, and execute from there. One implementation can be found in `dev-tools/minikube`, where you can use the setup script to declare which services you want to build directly from source. Alternatively, a more robust solution can be found by using a tool such as [Skaffold](https://skaffold.dev/)

Reopening this in case you have any other issues today, so others can see as well. We can close again on Monday / once all is up and running.

**Comment by huberv** [comment]
Hi @weberjm,

Thanks again for the extensive explanations! I had a look at the docs in the dev-tools folder, there are several caveats mentioned when trying to get OIH up and running locally on Windows...

I disabled the Kubernetes embedded in my Docker-Desktop installation and succeeded in running `wsl bash oih\dev-tools\minikube\setup.sh` (effectively using `minikube` and `kubectl` from within wsl2) in my wsl2 default distro (a Ubuntu 16.04).

Like others I stumbled on the issue of e.g. opening the K8s dashboard (see https://github.com/kubernetes/minikube/issues/5392) or any other URL from Windows... which does not work for some strange reason. However, using a browser from within wsl2 in conjunction with a Windows X-Server (like [VcXsrv](https://sourceforge.net/projects/vcxsrv/)) does the trick. That setup enables me to follow the instructions for running OIH the "Minikube way".

**Comment by RobinBrinkmann** [comment]
Hi @huberv,
happy to hear you made it work. As you said, local setup (especially under Windows) can be a bit tricky at times. In case you have learnings that may help others, please do not hesitate to suggest some additions to the documentation:
https://github.com/openintegrationhub/openintegrationhub.github.io
