### ISSUE TITLE
Migrate e.io scheduler service into OIH scheduler

### ISSUE THREAD

**Issue by drobiazko** [openintegrationhub/openintegrationhub#119]
As an OIH operator I want to have a scheduler that covers all required functionalities, so that flows can be scheduled properly.

**Further Description:**

The Elastic.io specific scheduler service will be open sourced and published within the Open Integration Hub repository.

Extract from https://github.com/openintegrationhub/openintegrationhub/issues/119#issuecomment-433831352:

> 1. we (as OIH) have scheduler service, but it is quite small and limited
> 2. we (as e.io) have scheduler service, it has more features, but it has a lot of e.io specific code.
> 
> So concept is next:
> Elastic.io changes scheduler service, extract e.io specific code into some pluggable parts. The rest is adapted to oih code requirements and published into OIH repo.

---

**Acceptance Criteria:**
- [ ] Service is production ready

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
@anton-kotenko you know the status of this issue or to whom I must turn to?
And are you able to estimate this one and issue #118 ?

**Comment by anton-kotenko** [comment]
Hi, @philecs 
As far as i understand the task:
1) we (as OIH) have scheduler service, but it is quite small and limited
2) we (as e.io) have scheduler service, it has more features, but it has a lot of e.io specific code.
So concept is next: 
e.io changes scheduler service, extract e.io specific code into some pluggable parts. The rest is adapted to oih code requirements and published into OIH repo.
Same story with #118.

About estimates: Both of this tasks are quite large, and I'd prefer not to estimate them without prior detailed look there, But at very-very first glance both may take from two weeks up to  month of work of one person.  
Other question related to this issue is actual plans, when we are going to do this. I suppose that plans should be discussed with @drobiazko. Also I think that as for now it should be assigned to @drobiazko, later somebody from e.io team will reassign it to himself.

**Comment by philecs** [comment]
@anton-kotenko perfect, thanks for the update :+1:

**Comment by pnedelko** [comment]
Implementation is done.
Requires testing and documentation.
