### ISSUE TITLE
Include optional callback execution in Event Bus error handling

### ISSUE THREAD

**Issue by SvenHoeffler** [openintegrationhub/openintegrationhub#1232]
In order to allow services to react to potential infrastructure outages more accurately, the Event Bus should be able to execute a callback function if connection to the queue is lost for whatever reason. The most suitable hook for this lies in the RabbitMqTransport.js, which will register any error or outage of the queue: https://github.com/openintegrationhub/openintegrationhub/blob/95ce2febadc9e7096b184584adc2becfa50ba68b/lib/event-bus/src/RabbitMqTransport.js

---

**Acceptance Criteria:**

- [x] Event Bus `connect()` method allows for an optional callback function to be passed in
- [x] Event Bus correctly executes the callback function in case of loss of connection

---

**Comment by winklerj** [comment]
In addition to improving how the eventbus handles lost connections and channels from RabbitMQ, I've come across similar issues in ferryman which separately implements similar amqp logic in the https://github.com/openintegrationhub/openintegrationhub/blob/master/lib/ferryman/lib/amqp.js file. 

For example I noticed that the error and close listener don't retry to connect. They only mark a boolean false to indicate the connection isn't active https://github.com/openintegrationhub/openintegrationhub/blob/master/lib/ferryman/lib/amqp.js#L36. There isn't logic to act on that information.

Also we have gotten into a situation where the channel or connection is closed because RabbitMQ was temporarily unavailable, but the publish function didn't check the connection/channel status.  This caused it to retry publishing but get the channel closed error each time ferryman tried to publish data. Here is the section with the publish retry logic, but doesn't check the connection and channel https://github.com/openintegrationhub/openintegrationhub/blob/master/lib/ferryman/lib/amqp.js#L271
