### ISSUE TITLE
Implement centralized flow logging functionality

### ISSUE THREAD

**Issue by SvenHoeffler** [openintegrationhub/openintegrationhub#1313]
In order to better track flow execution status and health, there should be a simple way to monitor logs from all currently active components at a single point of contact. In the case of a GCP deployment, the native Stackdriver API may be leveraged for this purpose.

Additionally, we should develop and document a best practice for the format of component's error logs, in order to more easily filter and interpret them.

---

**Acceptance Criteria:**

- [ ] Documented component error logging best practices
- [ ] Implemented prototype log fetching across several/all connector deployments

---

**Comment by jkopen** [comment]
# Component error logging best practices

Each component should wrap its functions in a try-catch block and emit an error message in the catch case. Furthermore, in case of any non-standard API response like status 500 the component also should send an error message.

To enable better analysis and monitoring of errors, each component ideally should emit error messages in a standardized format. The message should also contain sufficient information to identify the affected part of code.

## Format

Therefore, the error message should be an JSON object with the following attributes:

- timestamp
  *timestamp of the error message*
- componentName
  *identifier of the component*
- componentId
  *OIH id of the component*
- file
  *the file in which the error occurred*
- line
  *line of code the message is sent from*
- errorObject
  *Error object as parsable JSON-String*
- description
  *Optionally an error description as text*
- errorLevel
  *0 for errors caught in the main catch block. Otherwise, choose a higher number*

## Example:

```
try {
    ...call to api...
    if(response.status === 500) {
        ...emit error message with errorLevel 1...
    }
} catch (error) {
    const errorMessage = {
        timestamp: Date.now(),
        componentName: 'Component XY',
        componentId: 'a1234',
        file: __filename,
        line: 120,
        errorObject: error,
        description: 'API call failed for unknown reason',
        errorLevel: 0,
    };

    this.emit('error', errorMessage);
}
```

**Comment by RobinBrinkmann** [comment]
Backlog clean-up. Closing of outdated issues.
