### ISSUE TITLE
Rebound Not Functional

### ISSUE THREAD

**Issue by kerriannercrawford** [openintegrationhub/openintegrationhub#1315]
**Describe the bug**
Currently, the rebound queue is not operating as expected. The rebound messages are being sent to the orchestrator back end exchange, but that exchange has no routing for the rebounded message. Therefore, they are being dropped and never hitting the correct rebound queue. 

**Expected behavior**
The expectation would be a message would hit the rebound queue, go to the correct exchange for that component (if global) or step (if not) and be retried as needed. This is not happening.

**To Reproduce**

1. Send a rebound message 
2. See in the message logs that the exchange is not correct
3. Track in RabbitMQ, see the message come into the message queue but not successfully rebound. 

**Your OIH Setup Information**
Using OIH in GCP, but the rebound queue is not working in our cloud environment or on my local environment. Seems to be a bug that was not caught when transitioning from Sailor to Ferryman.

**Additional context**
I have been trying to debug this myself for awhile, but I think this is something that is going to need to be a ferryman change. After reviewing the code, I believe that this may be a solution, but I cannot test it myself so I'm not completely sure. 

https://github.com/kerriannercrawford/openintegrationhub/commit/a598db7e9a72245d3a2773f303400e94ec9bb364

**Comment by RobinBrinkmann** [comment]
Thanks @kerriannercrawford, we will look into it. What version of the framework are your running on?

**Comment by kerriannercrawford** [comment]
Thanks @RobinBrinkmann. Our GCP environment is running 21.1.0.

**Comment by heggert** [comment]
Right now our rebound mechanics are just broken...

After some reading and testing on the current master, I figured a possible reason for this in settings the orchestrator is passing as envs to each component.

https://github.com/openintegrationhub/openintegrationhub/blob/da80565202f403f4b4d586d85cc7ebf11e10f241/lib/ferryman/lib/amqp.js#L530

```javascript
        return this.sendToExchange(
            settings.BACKCHANNEL_EXCHANGE,
            settings.REBOUND_ROUTING_KEY,
            originalMessage.content,
            properties,
        );
```

`BACKCHANNEL_EXCHANGE` has value "orchestrator_backchannel" whereas `REBOUND_ROUTING_KEY` has "flow-xyz-step.rebound " or "component-abc.rebound" (for local or global components).

Those combinations simply do not exist within our auto-generated rabbitmq setup. 

Instead, It should be either 

```
Solution 1
"orchestrator_backchannel" and "orchestrator_backchannel.rebound"
-> The orchestrator would pick up this message and re-execute a step accordingly.
```
```
Solution 2
"flow-xyz" and "flow-xyz-step.rebound"
A component (flow step) would handle the rebound message itself.
```
The second looks more elegant to me.

On upcoming Wednesday we will discuss which type we are going to implement.

Thanks for submitting this issue, @kerriannercrawford. Feel free to be part of further discussion. ;)

**Comment by heggert** [comment]
We decided to follow the second solution. I will start working on this in about two weeks from now and supply some insights.

**Comment by heggert** [comment]
I applied the proposed changes. See https://github.com/openintegrationhub/openintegrationhub/pull/1322

Along the way, I recognized, that we now need to handle those messages appropriately.

In addition, we have to think about the also existing `requeue` queue as an alternative to the `rebound` queue, especially in what cases both queues should be used.

@kerriannercrawford  @jkopen @SvenHoeffler Please provide some feedback before we can progress with this issue.

**Comment by winklerj** [comment]
@heggert Is there documentation or could you explain the different purposes between `requeue` and `rebound`?  The functionality seems similar so I would like to understand the nuance between the two.

**Comment by heggert** [comment]
Since the original creators left the core dev-team years ago, we have to re-think what purpose those different queues serve. 

Let's have a look into a current queue setup for a flow consisting of just one local component.


![Bildschirmfoto von 2021-09-27 11-47-01](https://user-images.githubusercontent.com/1838660/134889025-9a2c4c42-471b-4ada-af4e-8a34ccd66963.png)

We see that the `requeue` routing key is bound to the same queue as the `input` routing key.

I assume, its use case is to trigger a component again (retry). Right now, as far as my understanding goes, the **ferryman does not handle this case**.

In contrast, the `rebound` routing key is bound to its own queue. With the latest changes provided by #1322 a rebound message now reaches the correct queue. 

However, it looks like, that we do not handle/ACK them. The big question is what should we use it for. As we already could use a `requeue` queue for retrying, a rebound queue should solve a different case. 

Maybe rejecting?

**Comment by winklerj** [comment]
@heggert Your message was helpful for me to potentially understand the difference. The intent of the rebound is to have a TTL before adding back to the messages queue. It looks like requeue will send the message to the end of the original queue immediately.

The rebound will try again after 15s, 30s, 1m, 2m, 4m, 8m, etc. It follows the design specified here https://www.cloudamqp.com/docs/delayed-messages.html.  Ferryman does this by specifying a TTL on the rebound queue, which will always timeout and the dead letter message queue will route to the original component messages queue.

**Comment by heggert** [comment]
@winklerj Thanks for providing this concept. Now I have a clearer view and my local tests work as expected. 

Unfortunately, now we need to talk about an `error` queue. 

If a rebound limit is reached currently our components will send a message to "BACKCHANNEL_EXCHANGE -> ERROR_ROUTING_KEY. 

![Bildschirmfoto von 2021-09-27 17-49-40](https://user-images.githubusercontent.com/1838660/134943287-c49c9656-e7f4-44df-b244-480b4b05cf00.png)

This leads to an error message being **unroutable**.

One approach to solve could be, creating an `error queue` the orchestrator is listening to. If an error message arrives it will be printed in STDOUT - as a starting point.

**Comment by winklerj** [comment]
@heggert I think what you propose is a good first step just so the error is logged somewhere and isn't lost.

In v1.x we created a flow history service which used the existing `component-events-collector` exchange and created a `flow-errors` queue to route all errors to that queue with `#.error`. Here is an image from a running environment:
![Screen Shot 2021-09-27 at 12 37 50 PM](https://user-images.githubusercontent.com/1112493/134950687-28bfbf25-fd32-461d-8374-6c7746e23c0c.png)

Without the flow-history service those errors were **unroutable** and had the same issue until I created that queue for our service.  It sounds like you are proposing the same approach only the component-orchestrator would be responsible and would log the error instead of persisting to a MongoDB database.

**Comment by winklerj** [comment]
@heggert It looks like there is still an issue with global components missing the new `NODE_EXCHANGE` environment variable.  It is working for local components by being add here https://github.com/blendededge/openintegrationhub/blob/master/lib/backend-commons-lib/src/QueueCreator.js#L310. But, it is not being added for global components here: https://github.com/blendededge/openintegrationhub/blob/master/lib/backend-commons-lib/src/QueueCreator.js#L370.  It is instead named `PUBLISH_MESSAGES_TO` which I believe was the previous name of the exchange. I remember seeing that commented out somewhere.
