### ISSUE TITLE
Collect requirements for Notification and Event Bus

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#133]
As a development lead I want to fully understand the scope of the notification and event bus service, so that my team and I are able to implement this service.

**Further description:**

Currently, a first [conceptional draft](https://github.com/openintegrationhub/Microservices/blob/MessageandEventBusConcept/MessageProcessing/MessageandEventBus.md) of the service exists. Nevertheless, no coherent understanding of the service across all partners. Thus, the output of this issue should be a requirement list for the subsequent creation of service specifications.

- [x] Collect and consolidate requirements from all partners

---

**Acceptance Criteria:**
- [x] Requirements are documented

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by sachmerz** [comment]
We do actually use GCP PubSub for our own services for loosely coupled communication. A similar approach in OIH with topics, subscribers and message publishing using RabbitMQ may come in handy. 

Our expectation would be:
* A lightweight setup using only RabbitMQ. Kafka or an Event Store with Event Sourcing for decoupled communication would be extreme, at least at current state of development
* There should be an OIH npm library which any OIH Service can use
* A sophisticated solution for topics authorization to limit the access to sensitive data published within that topic (doesn't RabbitMQ support this since version 3.7.0?)

**Comment by philecs** [comment]
Have we already scheduled an appointment for this discussion?

**Comment by philecs** [comment]
What is the status here?

**Comment by philecs** [comment]
As discussed in sprint review with @hschmidthh , @drobiazko and @pnedelko we should schedule a meeting between pavel and hansjörg (and possibly Sven) to discuss the notifcation and event bus.

**Comment by hschmidthh** [comment]
Updated the concept https://github.com/openintegrationhub/openintegrationhub/blob/updateMessageEventBusConcept/docs/services/MessageandEventBus.md
