### ISSUE TITLE
Ferryman - Upon receiving NULL message, the service stops polling for new messages. 

### ISSUE THREAD

**Issue by leejaycb** [openintegrationhub/openintegrationhub#1408]
**Describe the bug**
When an OIH container (base OIH service, or component) retrieves a `null` message from rabbitMQ, Ferryman returns null from the [decryptMessage function](https://github.com/openintegrationhub/openintegrationhub/blob/73d3a79116fee7dc9ce28137f06f46871d95d72b/lib/ferryman/lib/amqp.js#L194). I believe this is causing the service to get into a state where ferryman is no longer polling for new messages. I brought this up in the OIH slack with the proposal when a `null` message is received from rabbitMQ that we reject the message, in the same manner that we do [lower in the function](https://github.com/openintegrationhub/openintegrationhub/blob/73d3a79116fee7dc9ce28137f06f46871d95d72b/lib/ferryman/lib/amqp.js#L208) when encountering an error. 

**Expected behavior**
When a `null` message is received by ferryman, the service should accept/reject the message, report that it was null, and continue to poll for new messages. 

**To Reproduce**
We have not been able to successfully replicate the steps to get into this state. We currently believe it is due to rabbitmq / service containers being shuffled by GKE. I believe this is caused by rabbitMQ restarting / scaling the rabbitmq instance

**Screenshots**
No screenshots available, Logs below. These logs can be found across component as well as the OIH service containers. 

```
 {"name":"ferryman","hostname":"global-6171dd2a41b13b001b6dc3f7-59d7965fdb-zqch2","pid":1,"level":10,"msg":"Message received: null","time":"2022-03-24T08:14:56.350Z","v":0}
{"name":"ferryman","hostname":"global-6171dd2a41b13b001b6dc3f7-59d7965fdb-zqch2","pid":1,"level":40,"msg":"NULL message received","time":"2022-03-24T08:14:56.351Z","v":0}
```
```
{"name":"ferryman","hostname":"local-617c2ad4753ae6001b472b66.put-attributes-6548c5977b-bbczm","pid":1,"level":30,"msg":"Start listening for messages on flow-617c2ad4753ae6001b472b66:put-attributes:messages","time":"2022-03-29T08:30:28.475Z","v":0}
{"name":"ferryman","hostname":"local-617c2ad4753ae6001b472b66.put-attributes-6548c5977b-bbczm","pid":1,"level":10,"msg":"Message received: null","time":"2022-03-29T08:40:56.054Z","v":0}
{"name":"ferryman","hostname":"local-617c2ad4753ae6001b472b66.put-attributes-6548c5977b-bbczm","pid":1,"level":40,"msg":"NULL message received","time":"2022-03-29T08:40:56.054Z","v":0}
```

**Your OIH Setup Information**
OIH version v21.1.0, running in GCP - k8s
RabbitMQ v3.8.21 - 3 replicas
Ferryman version v1.5.3

**Additional context**

**Comment by weberjm** [comment]
Updating the issue with later information from Slack: 
- When attempting to update the empty return to a message reject, the user noticed that this would still cause the top reject() function to look for a message to provide for information. In this case, the message would not exist.

Following additional research, I discovered that this is a "known state" in amqplib that exists when a client is canceled by the RabbitMQ server:
> if we have a NULL message, it will probably fail either in the reject() function, or internally in amqplib, which also expects a message containing the Rabbit message format:
{
  content: Buffer,
  fields: Object,
  properties: Object
}
While considering how to handle this, I came across the following items, which MAY provide some insight into why the NULL messages are appearing also.
The last line of the documentation on [consuming](https://amqp-node.github.io/amqplib/channel_api.html#channelconsume) data for amqplib states that
>> If the [consumer is cancelled](http://www.rabbitmq.com/consumer-cancel.html) by RabbitMQ, the message callback will be invoked with null.

> So, it appears that at some point, your message consumer is being cancelled from somewhere else (because of queue deletion, etc.). Some of the RabbitMQ libraries have been set up to support this more "gracefully," such as having a handleCancel event listener. amqplib seems to take the "simple" route and just send a NULL message. The proper way to handle this is probably to have the component attempt to reconnect to RabbitMQ, and error and fail if that does not succeed.
However, assuming that the NULL message you are receiving is in fact due to a consumer cancellation, then a reject() is not a proper way to handle, and shouldn't be implemented.

Therefore, likely the only way to successfully handle this, is to re-start the `consume()` function of the ferryman. The Channel should still exist, or have been recreated in the case of a restart, and the consumer needs to be re-registered for that channel, since it has been canceled from the server. The ferryman consumer should not need to call `cancel()` itself in this case. 

The current chain of the function call for setting this up is in:
- ferryman.js:`run()` -> amqp.js:`listenQueue()` -> amqp.js:`decryptMessage()`

Currently, the NULL message can only be identified in the `decryptMessage()` function, but the re-connect functionality will need to be hoisted up to one of the higher functions.

**Comment by weberjm** [comment]
After additional review, and discussing with some of the original developers of this section of the code, there are some changes which will be made to the Ferryman.

Originally, it was intentionally coded so that if the channel is closed and a NULL message is received, the component would throw an error and end the process. Once the Pod in Kubernetes is terminated, the outstanding Deployment should create a new Pod, which will go through the process of re-connecting, starting up when Rabbit is available again.

Several years ago, the code was updated to handle the NULL message and not terminate. Although it prevented component deletions, it had the unintended effect of circumventing the intended re-connect process.

https://github.com/openintegrationhub/openintegrationhub/blob/c2acfd23679fcaef107466cd147e54a17fcbe9b4/lib/ferryman/lib/amqp.js#L192-L194

By throwing a descriptive error and allowing the component to complete, we should be able to have a more robust system available again with minimal changes. I am working this now.

**Comment by weberjm** [comment]
Updates to services and ferryman in the latest release have mitigated these problems, so that components will restart and then attempt to reconnect to RabbitMQ following a NULL message.
