### ISSUE TITLE
Centralize role definition in ICR

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#207]
**Further description:**

Currently ICR does not fetch roles from ICR but has hardcoded roles. `ADMIN`, `TENANT_ADMIN` & `TENANT_INTEGRATOR`.

- [ ] Roles should be defined centrally

---

**Acceptance Criteria:**
- [ ] Roles centrally defined and resusable

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by SvenHoeffler** [comment]
The roles with their derived permissions have been moved to the central configuration for better ease of use.
However, in the course of working this issue, it has become apparent that the use of Roles for the purposes of permissions is a by now outdated holdover from using an earlier version of the IAM. Rather than continuing on this path, it would be more effective and efficient to adjust the ICR to directly make use of the IAM's new Permission system. A new issue for this task has been created: #247
