### ISSUE TITLE
Provide Hierarchy and Relationship Management Requirements

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#392]
Provide Wice requirements for the hierarchy & relationship management services.

---

**Acceptance Criteria:**

- [ ] Requirements provided

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by pnedelko** [comment]
From @hschmidthh 's email:

Hierarchy & Relationship Management Requirements

Company: 
Author:

The current idea is that this services acts as an integration layer which provides functionalities such as aggregation and splitting. 

The integration layer is used to support integration patterns like splitter, filter, aggregator. It is also used to adapt application specific behavior, micro processes or APIs. The application specific behavior is explicitly modeled using the integration layer framework.

The Transformer is located within the SDF and not between source adapter and SDF adapter. The Smart Data Framework has mechanisms to decide if an object is complete and ready to be sent to the target system. 

Consequences and Requirements:

Data validation needs to be implemented within the SDF
=> Should this be obligatory or optional?
The Open Integration Hub has to know the restrictions for all connected applications. Each application has to communicate its restriction (minimal required attributes for a complete object) to the Open Integration Hub. If an update of the restrictions happens, these updates must be communicated to the OIH in order to ensure proper completeness checks 
=> How we handle the definitions and updates? (e.g. REST-Calls, Commands via the queue?)
The Open Integration Hub has to compare the current message with these requirements and has to decide if the object is sent to the target application.
=> In case of rejection, should the source and the target of the integration flow be informed about the rejection and when, how to handle this?
If the message is not ready to be sent it can/must be temporarily stored until missing information is available. 
=> where to store the message? (e.g. DB, queue)
It is not possible to request missing transformation from the SDF. The Connector must be able to read and write from the storage mentioned above. 
=> How to do this? (e.g. REST, command messages?)
If the predefined time period exceeds the message is discarded
=> How long should this period be?
Raw data storage must be triggered before the transformer therefore in the connector or SDF.
=> Where do we store the raw data?
