### ISSUE TITLE
Component orchestrator handles global IAM events

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#561]
According to GDPR (DSGVO) a user has the right that his/her data is deleted upon request.

Furthermore, if a user or tenant is deleted in IAM, each service that is holding information about this user/tenant has to delete this information or make it indecipherable.

In the current implementation the component orchestrator holds duplicates of the flows that are stored in the flow repository. Therefore component orchestrator also has to handle those events.

**Further description:**

- [ ] Subscribe to global IAM 
- [ ] Make user/tenant data indecipherable or delete it upon certain events

---

**Acceptance Criteria:**
- [ ] Component Orchestrator handles IAM global events appropriately 

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by pnedelko** [comment]
Component Orchestrator stores not full copy of flows, but only [2 fields](https://github.com/openintegrationhub/openintegrationhub/blob/master/services/component-orchestrator/src/models/Flow.js#L4-L7): `graph` and `status`. Therefore it doesn't know whom that flow belongs to and can't properly react on `iam.user.deleted` event.

But we need to implement some cleanup system, so that no orphaned flows would keep running after a user has been deleted. I would propose to make it in the following way:
1. Flow repo could send a `flow.deleted` event when there no more owners left in owner array (or some other condition) and the flow is gonna be deleted. (Or `flow.stopping`, when the flow stays in the DB).
2. Component Orchestrator reacts on this event and stops the corresponding flows and deletes them from the DB.

What do you think guys?

**Comment by philecs** [comment]
Closed in favor of #650
