### ISSUE TITLE
Web UI: graphic updates

### ISSUE THREAD

**Issue by RobinBrinkmann** [openintegrationhub/openintegrationhub#633]
This issue summarizes non-functional changes to the Web UI.

**Further description**

Most changes are minor "cosmetic" improvements in order to enhance user experience.

Changes regarding the representation of components may require additional functionality of component repository.

---

**Acceptance Criteria:**
- [x] menu icons are updated (min. users and components)
- [x] change timestamp format
- [x] pre-filled template when adding new flow
- [x] pre-filled template when adding new component
- [x] show component logos in component repo and flows
- [x] show flows as diagram, replacing current node and edge description
- [x] show available actions and triggers for components 
- [x] visualize flow status

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by falkvoigt** [comment]
Last open step needs information coming from component-repo

**Comment by philecs** [comment]
Findings:

- When adding a role and assigning it to a user while removing all other roles, the web ui still displays the user's old role instead of the new one
- It's possible to add "empty" roles for a user (see graphic below)
![image](https://user-images.githubusercontent.com/29949654/63437064-27fbe180-c42a-11e9-8160-04951ac66594.png)
