### ISSUE TITLE
Review CRUD Monitoring Concept

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#71]
The existing CRUD Monitoring concept must be reviewed by the workgroup

Further description:

Wice already created a concept for the service [**CRUD monitoring**](https://github.com/openintegrationhub/Microservices/blob/master/ManagementServices/CRUDMonitoring.md) that must be reviewed by each workgroup member.

---

**Acceptance Criteria:**
- [ ] Concept reviewed by workgroup
- [ ] Accepted by Workgroup

**Comment by philecs** [comment]
@hschmidthh will send snippet from TVB regarding CRUD monitoring to workgroup

**Comment by sachmerz** [comment]
The current state of CRUD Monitoring concept does not go into much detail, probably because it's dependency SDF is not yet specified in detail.

Our feedback for current state is:

Logstash sounds like a neat solution. The logs created by Smart Data Framework (or another OIH Service) should ideally be in JSON format.
Processing of logs is ideally loosely coupled allowing to swap Logstash with any other log processing software or service.
