### ISSUE TITLE
Flow - error 404 after start

### ISSUE THREAD

**Issue by lgeorgiev** [openintegrationhub/openintegrationhub#746]
**Describe the bug**
When I start the Flow, the status changes from "starting" to "active", but Flow disappears from the list. 
I noticed that the "name" and "owner" disappear after activation. 

**To Reproduce**
1. Click on the ADD+ button
2. Click on the Start button
3. Refresh the page (/flows)

**Screenshots**
![flow-404](https://user-images.githubusercontent.com/1999598/64684014-fe643200-d48c-11e9-80e2-f7ba5d751912.jpg)

**Comment by RobinBrinkmann** [comment]
Thanks for letting us know. Do you run an Open Integration Hub locally (under what OS) or on GCP?

**Comment by lgeorgiev** [comment]
The OIH works locally (https://github.com/openintegrationhub/openintegrationhub/tree/master/minikube).
- Windows 10, 
- RabbitMQ 3.7.17
- Erlang 22.0

**Comment by SvenHoeffler** [comment]
Hi, I have been able to reproduce the error, it appears to be related specifically to the local installation somehow. I'll investigate further and let you know once I've figured something out.

**Comment by SvenHoeffler** [comment]
Found the issue, the secret was misconfigured and lead to two services attempting to write to the same database, accidentally deleting the flow. The fix is in the pipe and should be online later today. As some database paths have changed, the easiest way to apply it would be to nuke your local installation and set it up again from the top with the fixed files.
