### ISSUE TITLE
IAM has potential security vulnerabilities

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#86]
IAM/package-lock.json has potential security vulnerabilities.

**Further description:**

![image](https://user-images.githubusercontent.com/29949654/44918500-70af1c00-ad3b-11e8-96f5-dfbe559d3a7b.png)

---

**Acceptance Criteria:**
- [ ] Security Vulnerabilities solved

**Comment by sachmerz** [comment]
Updated `node-jose` dependency.

Currently, `npm audit` shows one of the dependencies of the `mockgoose` library to have a high vulnerability. There is an open pull request for Mockgoose, which is supposed to fix this issue: https://github.com/Mockgoose/Mockgoose/pull/79
We use `mockgoose` only in development and in unit tests, which is why this shouldn't be an issue in production environment.
