### ISSUE TITLE
Research options for a connector builder

### ISSUE THREAD

**Issue by RobinBrinkmann** [openintegrationhub/openintegrationhub#957]
In order to make development of new connectors easier, we want to investigate ways to automate creation of new connectors. Focus should first be on the apdaters, as transformers are most likely highly indivudalized for production. 

Outcome of this issue shall be:

- [x] a detailed description of the scope for a connector builder
- [x] a description of possible technical solutions and concepts
- [x] an evlatuation of these options with pros / cons

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by blaggacao** [comment]
If in-cluster building is on the list: https://github.com/GoogleContainerTools/kaniko

For a node-js asyncapi-based template: https://github.com/asyncapi/nodejs-template

See also: https://www.asyncapi.com/docs/tooling/#codegens

**Comment by RobinBrinkmann** [comment]
Thanks for your suggestion and also the discussion yesterday. Please drop in any other thoughts in here.

**Comment by blaggacao** [comment]
We tested to openapi typescript builder it has nice semantics, and produces prettry complete output. One ought to cleanup any openapi document beforehand, though, since all collaterals (examples, etc) are also codified. Maybe asyncapi has the better builders.

It would also be interesting to explore the possibility of usi g a compiled language, especially golang, which is known for pioneering the field of code generators (standard everyday practice in go). Such pathway would probably require the ferryman to become a pure library in that language &mdash; and hopefully others, too.

**Comment by RobinBrinkmann** [comment]
With #1142 we may get close to a working version of a generator soon. This issue will stay open for now, in case we see the need to find alternatives to the component generator by Deutsche Telekom.

**Comment by RobinBrinkmann** [comment]
We are currently working on implementation (#1173) of a Generator and have a first working version: https://github.com/openintegrationhub/component-generator
