### ISSUE TITLE
Add Flow Template objects for reusable flows

### ISSUE THREAD

**Issue by weberjm** [openintegrationhub/openintegrationhub#978]
As a User, I want to be able to create Flow Templates so that I can reuse commonly deployed flows without rebuilding them each time.

Further description:
Currently, the Flow repository holds only a record of specific, fully-configured Flows. By implementing Flow Templates, Users will be able to find and select interesting flows which are commonly implemented between Connectors. This provides significant time savings when used in a multi-tenant environment or across a larger organisation. 

The Flow Templates will contain
- References to the used Components
- Flow Steps to be executed
- Variables which need to be provided with values to generate a Flow
---

**Acceptance Criteria:**
- [x] Flow Template object is created and accessible by API (under Flow Repository or somewhere else?)
- [x] Flow Templates have functionality to generate Flows

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)

**Comment by blaggacao** [comment]
Since flow definitions are json &mdash; I suspect &mdash; an overlay approach could be used to transform any existing flow with a jsonata expression &rarr; provide a jsonata rpc that refurns a new flow based off an existing flow + jsonata expression.

Pros: 👍 
-  That way, no extra templating infrastructure (new object model) is required.
- It is more expressive for the (api) user.
- Blessed flows can be marked into "templates" simply by a boolean.

Cons: 👎 
- The scoped variable environment of a pure template based approach reduces complexity when setting up a template based flow. &mdash; this can be solved by ui componets that generate jsonata expressions under the hood, too.
